name: Tailscale Demo

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install ping
        run: sudo apt-get update && sudo apt-get install -y iputils-ping

      - name: Tailscale
        uses: tailscale/github-action@v3
        # https://github.com/tailscale/github-action
        with:
          authkey: ${{ secrets.AUTHKEY }}
          args: ${{ secrets.TAILSCALE_ARGS }}
          # tailscaled-args: "--tun=userspace-networking"
          tags: tag:ci

      - name: display tailscale ip
        run: echo $(ip -f inet addr show tailscale0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')

      - name: tailscale ping
        if: success() || failure()
        run: tailscale ping arm-us-east-1

      # always logout
      - name: tailscale logout
        if: success() || failure()
        run: sudo tailscale logout
